In [ ]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
print( len(iris) )
print( iris.keys() )
print( type(iris) )

# Data in scikit-learn is in most cases saved as two-dimensional Numpy arrays with the shape (n, m)
n_samples, n_features = iris.data.shape
print('Number of samples:', n_samples)
print('Number of features:', n_features)
print(iris.data[0])

# 
print(iris.target)
print( len(iris.target) )
print(iris.data.shape)
print(iris.target.shape)

#
np.bincount(iris.target)
print( len(iris.target_names) )
print(iris.target_names)

# 
print(iris.data[iris.target==1][:5])
print()
print(iris.data)

In [ ]:
# Train and Test Sets
print(iris.target)
print( len(iris.target) )
print()

# 
indices = np.random.permutation(len(iris.data))
print(indices)
print( len(indices) )
print()

n_test_samples = 12
learnset_data = iris.data[indices[:-n_test_samples]]
learnset_labels = iris.target[indices[:-n_test_samples]]
testset_data = iris.data[indices[-n_test_samples:]]
testset_labels = iris.target[indices[-n_test_samples:]]
print(learnset_data[:4], learnset_labels[:4])
print(testset_data[:4], testset_labels[:4])
print()

In [ ]:
# 
from sklearn.model_selection import train_test_split

data, labels = iris.data, iris.target
res = train_test_split(data, labels, train_size=0.8, test_size=0.2, random_state=42)
train_data, test_data, train_labels, test_labels = res

print("Labels for training and testing data")
print(test_data[:5])
print(test_labels[:5])
print()

Labels for training and testing data
[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]]
[1 0 2 1 1]

